backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tagline", name: "tagline", widget: "string" }
      - { label: "Full width", name: "fullWidth", widget: "boolean" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Display position", name: "displayPosition", widget: "number" }
      - label: "Text color"
        name: "textColor"
        widget: "select"
        options:
          - { label: "Black", value: "text-black" }
          - { label: "White", value: "text-white" }
      - { label: "Background color", name: "backgroundColor", widget: "string" }
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: "image",
          allow_multiple: false,
        }
      - label: "Content"
        name: "content"
        widget: "list"
        types:
          - label: "Text Block"
            name: "textBlock"
            widget: "object"
            fields:
              - {
                  label: "Title",
                  name: "textTitle",
                  widget: "string",
                  required: false,
                }
              - { label: "Text", name: "textBody", widget: "markdown" }
          - label: "Images"
            name: "images"
            widget: "object"
            fields:
              - { label: "Full width", name: "fullWidth", widget: "boolean" }
              - { label: "Carrousel", name: "carrousel", widget: "boolean" }
              - {
                  label: "Images",
                  name: "images",
                  widget: "image",
                  allow_multiple: true,
                }
