backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

fields: &FIELDS
  - { label: "Title", name: "title", widget: "string" }
  - { label: "Tagline", name: "tagline", widget: "string" }
  - { label: "Publish Date", name: "date", widget: "datetime" }
  - { label: "Display position", name: "displayPosition", widget: "number" }
  - label: "Text color"
    name: "textColor"
    widget: "select"
    options:
      - { label: "Black", value: "text-black" }
      - { label: "White", value: "text-white" }
  - { label: "Draw color", name: "drawColor", widget: "string" }
  - { label: "Header background color", name: "headerColor", widget: "string" }
  - {
      label: "Content background color",
      name: "backgroundColor",
      widget: "string",
    }
  - label: "Content"
    name: "content"
    widget: "list"
    types:
      - label: "Text block"
        name: "textBlock"
        widget: "object"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - { label: "Text", name: "body", widget: "markdown" }
      - label: "Images block"
        name: "imagesBlock"
        widget: "object"
        fields:
          - label: "Images size"
            name: "size"
            widget: "select"
            default: "medium"
            options:
              - { label: "Extra small", value: "extra-small" }
              - { label: "Small", value: "small" }
              - { label: "Medium", value: "medium" }
              - { label: "Large", value: "large" }
              - { label: "Full width", value: "fullWidth" }
          - label: "Should display as carrousel"
            name: "carrousel"
            widget: "boolean"
            default: false
            required: false
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: Image Description, name: "alt", widget: string }
              - label: Image title
                name: "title"
                widget: string
                required: false
              - label: "Image title position"
                name: "titlePosition"
                widget: "select"
                default: "center"
                options:
                  - { label: "Left", value: "left" }
                  - { label: "Center", value: "center" }
                  - { label: "Right", value: "right" }

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - *FIELDS
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields: *FIELDS
  - name: "footer"
    label: "Footer links"
    folder: "content/footer"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - label: "Links"
        name: "links"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Url", name: "url", widget: "string" }
  - name: "metaData"
    label: "Meta data"
    folder: "content/metaData"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "LinkedIn url", name: "linkedin", widget: "string" }
      - label: "Author"
        name: "author"
        widget: "object"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Summary", name: "summary", widget: "string" }
